# Generated by Django 2.0.2 on 2019-02-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader', '0006_auto_20181021_1620'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Chapter')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Page')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
