# Generated by Django 2.1 on 2018-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the series.'),
        ),
    ]
