# Generated by Django 2.0.2 on 2018-09-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('reader', '0002_reader_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group'),
        ),
    ]
