# Generated by Django 2.1 on 2018-10-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_float_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='The name of the category. Must be unique.', max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='A description for the category.', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(blank=True, to='reader.Category'),
        ),
    ]
