# Generated by Django 2.1.5 on 2019-02-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='url',
        ),
    ]
