BOTS = [
    'Advanced Email Extractor',
    'AhrefsBot',
    'Atomic_Email_Hunter',
    'atSpider',
    'autoemailspider',
    'BlackWidow',
    'Boston Project',
    'bwh3_user_agent',
    'China Local Browse',
    'ContactBot',
    'ContentSmartz',
    'DataCha0s',
    'Dataprovider.com',
    'del.icio.us-thumbnails',
    'Demo Bot',
    'DigExt; DTS Agent',
    'DotBot',
    'Educate Search',
    'efp@gmx.net',
    'EmailCollector',
    'EmailSiphon'
    'EmailWolf',
    'emailspider',
    'ExtractorPro',
    'Franklin Locator',
    'Full Web Bot',
    'Guestbook Auto Submitter',
    'Industry Program',
    'Indy Library',
    'Iplexx Spider',
    'ISC Systems iRc Search',
    'IUPUI Research Bot',
    'jaja-jak-globusy.com',
    'JOC Web Spider',
    'LetsCrawl.com',
    'LightspeedSystemsCrawler',
    'Lincoln State Web Browser',
    'LMQueueBot',
    'LWP::Simple',
    'Mac Finder',
    'Mail.RU_Bot',
    'MFC Foundation Class Library',
    'Microsoft URL Control',
    'Missauga Locate',
    'Missigua Locator',
    'Missouri College Browse',
    'Mizzu Labs',
    'Mo College',
    'MVAClient',
    'NameOfAgent (CMS Spider)',
    'NASA Search',
    'netcraft.com',
    'NEWT ActiveX',
    'Nsauditor',
    'Port Huron Labs',
    'Production Bot',
    'Program Shareware',
    'psycheclone',
    'scan4mail',
    'searchbot',
    'SemrushBot',
    'ShablastBot',
    'SiteSucker',
    'snap.com beta crawler',
    'Snapbot',
    'Sogou',
    'sogouspider',
    'sohu agent',
    'Surfbot',
    'TrackBack',
    'Under the Rainbow',
    'VadixBot',
    'Wells Search',
    'Wep Search',
    'WebCapture',
    'WebEMailExtrac',
    'WebFetch',
    'Website eXtractor',
    'WebVulnCrawl',
    'Wysigot'
]
