BOTS = [
    r'(auto)?emailspider',
    r'(Contact|LMQueue)Bot',
    r'^$',  # empty UA
    r'^\w?(Browse|Surf|Eval)',
    r'^\w?Surf15a',
    r'Advanced Email Extractor',
    r'Atomic_Email_Hunter',
    r'atSpider',
    r'BlackWidow',
    r'Boston Project',
    r'bwh3_user_agent',
    r'China Local Browse',
    r'ContentSmartz',
    r'DataCha0s',
    r'del\.icio\.us-thumbnails',
    r'Demo Bot \w+ 16b',
    r'DigExt; DTS Agent',
    r'Educate Search',
    r'efp@gmx\.net',
    r'Email(Collector|Siphon|Spider|Wolf)',
    r'ExtractorPro',
    r'Franklin Locator',
    r'Full Web Bot',
    r'Guestbook Auto Submitter',
    r'Industry Program',
    r'Indy Library',
    r'Iplexx Spider',
    r'ISC Systems iRc Search',
    r'IUPUI Research Bot',
    r'jaja-jak-globusy\.com',
    r'Jo(Bo|C Web Spider)',
    r'LetsCrawl\.com',
    r'Lincoln State Web Browser',
    r'LWP::Simple',
    r'Mac Finder',
    r'Mail\.RU_Bot',
    r'MFC Foundation Class Library',
    r'Microsoft URL Control',
    r'Miss(aug|igu)a Locat(e|or)',
    r'Missouri College Browse',
    r'Mizzu Labs',
    r'Mo College',
    r'MVAClient',
    r'NameOfAgent \(CMS Spider\)',
    r'NASA Search',
    r'netcraft\.com',
    r'NEWT ActiveX',
    r'Nsauditor',
    r'Port Huron Labs',
    r'Production Bot',
    r'Program Shareware',
    r'psycheclone',
    r'scan4mail',
    r'searchbot',
    r'SemrushBot',
    r'ShablastBot',
    r'SiteSucker',
    r'snap\.com beta crawler',
    r'Snapbot',
    r'sogou (\w+\s)?spider',
    r'sohu agent',
    r'TrackBack',
    r'Under the Rainbow',
    r'VadixBot',
    r'We(lls|p) Search',
    r'WebCapture',
    r'WebEMailExtrac',
    r'WebFetch',
    r'Website eXtractor',
    r'WebVulnCrawl',
    r'Wysigot'
]

