# Generated by Django 2.0.2 on 2018-09-05 14:18

import MangAdventure.modules.storage
import MangAdventure.modules.uploaders
import MangAdventure.modules.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The group's proper name.", max_length=250)),
                ('website', models.URLField(help_text="The group's website.")),
                ('email', models.EmailField(blank=True, help_text="The group's contact e-mail address.", max_length=254)),
                ('discord', models.URLField(blank=True, help_text="Invite link for the group's discord guild.")),
                ('twitter', models.CharField(blank=True, help_text="The group's twitter handle.", max_length=15)),
                ('description', models.TextField(blank=True, help_text='The description of the group.')),
                ('logo', models.ImageField(help_text='Upload a group logo. Its size must not exceed 2 MBs.', storage=MangAdventure.modules.storage.OverwriteStorage(), upload_to=MangAdventure.modules.uploaders.group_logo_uploader, validators=[MangAdventure.modules.validators.FileSizeValidator(max_mb=2)])),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The member's name.", max_length=100)),
                ('twitter', models.CharField(blank=True, help_text="The member's twitter handle.", max_length=15)),
                ('discord', models.CharField(blank=True, help_text="The member's discord name (and id).", max_length=32)),
                ('avatar', models.ImageField(help_text='Upload a member avatar. Its size must not exceed 2 MBs.', storage=MangAdventure.modules.storage.OverwriteStorage(), upload_to=MangAdventure.modules.uploaders.member_avatar_uploader, validators=[MangAdventure.modules.validators.FileSizeValidator(max_mb=2)])),
                ('group', models.ForeignKey(help_text='The Group the member is part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LD', 'Leader'), ('TL', 'Translator'), ('PR', 'Proofreader'), ('CL', 'Cleaner'), ('RD', 'Redrawer'), ('TS', 'Typesetter'), ('RP', 'Raw Provider')], max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='groups.Member')),
            ],
        ),
    ]
