name: Deploy

run-name: ${{github.event.workflow_run.head_commit.message}}

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [master]

jobs:
  render:
    name: "Render"
    runs-on: ubuntu-latest
    environment:
      name: render
      url: https://mangadventure.onrender.com/
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Check for file changes"
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_ignore: |-
            LICENSE
            README.md
            MANIFEST.in
            .editorconfig
            .gitattributes
            .dockerignore
            .gitignore
            .github/**
            docker/**
            docs/**
            */tests/**
      - name: "Deploy on Render"
        if: steps.changed-files.outputs.any_changed == 'true'
        run: curl -Ssf "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{secrets.RENDER_DEPLOY_HOOK}}
