name: Post-release

on:
  release:
    types: ["released"]

jobs:
  webhook:
    name: "Discord webhook"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mangadventure'
    steps:
      - name: "Send data to Discord"
        env:
          RELEASE_BODY: ${{github.event.release.body}}
          RELEASE_NAME: ${{github.event.release.tag_name}}
          RELEASE_WEBHOOK: ${{secrets.RELEASE_WEBHOOK}}
        run: |-
          jq --arg name "$GITHUB_ACTOR" \
             --arg author_url "$GITHUB_SERVER_URL/$GITHUB_ACTOR" \
             --arg icon_url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER.png?s=40" \
             --arg title "New release published: $RELEASE_NAME" \
             --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/$RELEASE_NAME" \
             --arg description "$RELEASE_BODY" \
             -Mn '{
               username: "GitHub",
               avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
               embeds: [{author: {$name, $icon_url, url: $author_url}, $url, $title, $description}]
             }' | curl -d@- -Ssf "$RELEASE_WEBHOOK" -H 'Content-Type: application/json' \
                       -A "GitHub-Actions ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY, v0.1)"
