name: Release

on:
  push:
    tags: ['*']

jobs:
  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mangadventure'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python
      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v2

  release:
    name: "Create release"
    needs: [codeql]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mangadventure'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Verify release version"
        run: >-
          grep -q "__version__ = '${GITHUB_REF_NAME#v}'" MangAdventure/__init__.py &&
          grep -q "@${GITHUB_REF_NAME}#egg=mangadventure\"" docs/install.rst &&
          grep -q "@${GITHUB_REF_NAME}#egg=mangadventure\[" docs/install.rst &&
          grep -q "^${GITHUB_REF_NAME}$" docs/changelog.rst
      - name: "Mark previous prerelease"
        continue-on-error: true
        run: |-
          GH_API="$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases"
          export $(curl -Ssf "$GH_API/latest" | \
            jq -r '"id=\(.id) tag=\(.tag_name)"')
          # skip if the new tag has a different minor version
          : ${GITHUB_REF##*/}; [[ ${_%.*} == ${tag%.*} ]] || exit 0
          curl -Ssf "$GH_API/$id" -o /dev/null -XPATCH \
            -d '{"prerelease":true}' -H "Authorization: Token $GITHUB_TOKEN"
          curl -Ssf "$RTFD_API/mangadventure/versions/$tag/" -XPATCH \
            -d 'active=false' -H "Authorization: Token $RTFD_TOKEN"
        env:
          RTFD_TOKEN: ${{secrets.RTFD_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RTFD_API: https://readthedocs.org/api/v3/projects
      - name: "Parse release body"
        run: make changes > changes.md
        working-directory: ./docs
      - name: "Upload release"
        uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          bodyFile: docs/changes.md
          allowUpdates: true

  docker:
    name: "Build Docker image"
    needs: [codeql]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mangadventure'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to the Container registry"
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: "Extract metadata for Docker"
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: ghcr.io/mangadventure/app
      - name: "Build and push Docker image"
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
